##################################################################
#                          YEAH NODE                          #
##################################################################
version: "3"
services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
    networks:
      - redis
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - redis
  web:
    volumes:
      - ${WEB_SOURCE_DIR}:/source
    build:
      context: ./node
      dockerfile: Dockerfile
    expose:
      - "3000"
      - "3080"
    networks:
      - redis

networks:
  redis:
    driver: bridge
