##################################################################
#                          YEAH NODE                          #
##################################################################
version: "3"
services:
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile
  proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/proxy/nginx.conf:/etc/nginx/nginx.conf
  web:
    volumes:
      - ./source:/source
    build:
      context: ./node
      dockerfile: Dockerfile
    expose:
      - "3000"
      - "3080"
